# Generated by Django 4.2.3 on 2023-09-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('voicePart', models.CharField(max_length=30)),
                ('board', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('voicePart', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='exampleModel',
        ),
    ]
