# Generated by Django 4.2.3 on 2023-09-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0002_boardmember_member_delete_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='board',
            field=models.CharField(max_length=50),
        ),
    ]
