# Generated by Django 4.2.3 on 2023-09-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0004_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
