# Generated by Django 4.2.3 on 2023-09-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0005_contactmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='time_sent',
        ),
    ]
