# Generated by Django 4.2.3 on 2023-09-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0006_remove_contactmodel_time_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
