# Generated by Django 4.2.3 on 2023-09-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0008_alter_contactmodel_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='contactModel',
        ),
    ]
