# Generated by Django 4.2.5 on 2023-09-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0009_contactsubmission_delete_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TritoneSpotifyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
                ('spotify_url', models.URLField()),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
