# Generated by Django 4.2.3 on 2023-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0011_member_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='boardMember',
        ),
        migrations.AddField(
            model_name='member',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
