# Generated by Django 4.2.3 on 2023-09-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0013_alter_member_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='voicePart',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
