# Generated by Django 4.2.3 on 2023-09-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0014_alter_member_voicepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
