# Generated by Django 4.2.3 on 2023-09-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0015_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='altText',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
