# Generated by Django 4.2.3 on 2023-09-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0016_photo_alttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='classLevel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='funFacts',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='hometown',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
