# Generated by Django 4.2.3 on 2023-09-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0017_member_classlevel_member_funfacts_member_hometown'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='major',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
