# Generated by Django 4.2.3 on 2023-09-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0018_member_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
