# Generated by Django 4.2.3 on 2023-09-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0019_alter_member_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
